#!/usr/bin/env python3
"""Regenerate registry/gloss-index.md from decks/*.json. Run by build.sh."""
import json, glob, os, re, collections, datetime

rows = []
for f in sorted(glob.glob("decks/*.json")):
    d = json.load(open(f, encoding="utf-8"))
    for c in d["cards"]:
        if c["type"] != "bidir":
            continue
        term = re.sub(r"<[^>]+>", "", c["term"]).strip()
        gloss = re.sub(r"<[^>]+>", "", c["meaning"]).strip()
        key = gloss.split("—")[0].split(";")[0].split(",")[0].strip().lower()
        rows.append((key, term, gloss, d["course"], c["id"]))

bykey = collections.defaultdict(list)
for k, t, g, co, i in rows:
    bykey[k].append((t, g, co, i))
collisions = {k: v for k, v in bykey.items() if len({t for t, _, _, _ in v}) > 1}

out = ["# Gloss Index", "",
       "Collection-wide. Every English gloss on a bidirectional note, so a new term can",
       "be checked for collision **before** it is written. Two Arabic words sharing one",
       "gloss makes the meaning→term direction unanswerable and turns both into leeches.",
       "",
       f"Generated by `build.sh` on {datetime.date.today().isoformat()} — do not edit by hand.",
       "The rule is in `skill/references/card-design.md` §8. For the mirror case — one",
       "Arabic word with two senses across sciences — see `skill/references/shared-terms.md`.",
       "", "## Collisions — both cards need a disambiguator", ""]
if collisions:
    out += ["| Gloss key | Terms | Courses | Ids |", "|---|---|---|---|"]
    for k, v in sorted(collisions.items()):
        out.append(f"| {k} | {' · '.join(t for t,_,_,_ in v)} | "
                   f"{' · '.join(sorted({c for _,_,c,_ in v}))} | "
                   f"{' '.join(i for _,_,_,i in v)} |")
else:
    out.append("None. Regenerated on every build.")
out += ["", "## Full index", "",
        "| Gloss key | Term | Full gloss | Course | Id |", "|---|---|---|---|---|"]
for k, t, g, co, i in sorted(rows):
    out.append(f"| {k} | {t} | {g[:70]} | {co} | {i} |")

open("registry/gloss-index.md", "w").write("\n".join(out) + "\n")
print(f"  gloss-index.md: {len(rows)} glosses, {len(collisions)} collision(s)")
for k, v in collisions.items():
    print(f"    COLLISION: {k} -> {[t for t,_,_,_ in v]}")
